spring.application.name=movie-match-backend

# Corrected key and added database name 'movie-match'
spring.mongodb.uri=mongodb+srv://marwenjammazi171_db_user:fTOs9yKDqHzrnmJB@cluster0.x0fmscz.mongodb.net/movie-match?retryWrites=true&w=majority
server.port=8080
//marwenjammazi171_db_user
//fTOs9yKDqHzrnmJB